<a href="https://colab.research.google.com/github/listpplo/tensorflow_learning/blob/main/00_tensorflow_Fundamentals_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Fundamental concepts of tensorflow**

we are going to create the first tensor
Learnings:
* Introduction to tensors 
* puting and getting information from tensors
* Manipulting tensors 
* Tensor and numpy
* using @tf.function 
* using GPUS with Tensorflow (or tpu)

#INTRODUCTION TO TENSORS

In [ ]:
import tensorflow as tf         #importing tensor flow as tf
print(tf.__version__)

2.9.2


In [ ]:
#creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# cheacking the number of dimensions of a tensors (ndim)
scalar.ndim

0

In [ ]:
#crating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check the dimension of our vector
vector.ndim

1

In [ ]:
#creating a matrix(that has more than one dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix

# if we have data type error we can manupulate the data type
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#creating a tensor 
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                      [10,11,12]],
                       [[12,13,14],
                       [14,15,16]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[12, 13, 14],
        [14, 15, 16]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## what we'have created so far
* Scalar : a single number
* Vector : a number with direction(e.g wind speed with direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an n dimensional array of numbers ( 0-dimensional : scalar and so on)

#Creating tensors with tf.variable

Generally the tensors are **immutable** but by utilising the **tf.variable** we can make a variable tensor

In [ ]:
changeable_tensor = tf.Variable([10,7])

In [ ]:
unchangable_tensor = tf.constant([10,7])
changeable_tensor , unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#let's change one of the element of changeable_tesnsor

changeable_tensor[0] = 9  # not the correct way
changeable_tensor

TypeError: ignored

In [ ]:
# now we try tensor[n].assign -- for variable tensor
changeable_tensor[0].assign(7)   # correct way
changeable_tensor

In [ ]:
unchangable_tensor[0].assign(5)

#Note
We don't need to create tensor for ourselves the tesnor flow algorithm does this for us in the backgroud.

If needed use tf.constant() method and down the line **covert it as per need into variable**

##Creating Random Tensors

Random tensors are tensors of some abitrary size which contains random numbers

In [ ]:
# create two random tensor 
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 =random_1.normal(shape=(3,2))
random_1

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2, random_1,random_1 == random_2   ## checking they are equal or not

Why we need to shuffel the input value ?


To stop the ai model to get to habituated to only one type of input.

In [ ]:
#shuffel a tensor (valuable if we want to shuffel the data, so that inheart data does not effect learing)
not_shuffled = tf.constant([[10,7],[3,4],[5,6]])
not_shuffled
# shuffled our non-shuffled tensor
tf.random.shuffle(not_shuffled)


In [ ]:
not_shuffled

In [ ]:
#shuffel our non shuffled tensor
tf.random.set_seed(42)   #globle level seed
tf.random.shuffle(not_shuffled,seed =42) #operation level seed


#**Exercise** : Read through random seed genration and write five random tensor and shuffel them 

**Notes** : There are two types of seeds :-
          1. operational level -- used for basic operatios 
          2. Global level - used at global level to generate 

if the seeds are not defined insode the code the tf will select a random code for the operation.
**So,if the program to run depends on a specific seed we need to define the seed in the code.**

#Global level Seed
*tf.random.set_seed(Value)*   -- **Sets the  value of the global scalar**

#Operational level seed
*tf.random.shuffle(tensor_name, seed = Value)*  -- **operationla level seed**


>Seeds provide the basics how to start the generation of the random variable if we use diffrent seeds the shuffleing or the generation will yeild different results.

> **"But to get reproducable randomness we need to set the global seed and the operational seed"**

In [ ]:
from tensorflow.python.ops.variables import Variable
#That is if we consider two tensors generated with two different seeds they will not match even if we have defined the same global tensor

tf.random.set_seed(29)   #GLobal level tensor
tensor_A = tf.Variable([4,2])     # Defining variable tensor
tensor_B =tf.Variable([4,2])

tensor_A = tf.random.uniform([4,2])   # Both the tensor generator have different operational level seeds because we do not have defined the seeds explictly.
tensor_B = tf.random.uniform([4,2]) 

tensor_A == tensor_B

In [ ]:
# To generate tensor with same seed
tensor_C = tf.Variable([4,2])
tensor_D = tf.Variable([4,2])

tensor_C = tf.random.uniform([4,2], seed = 42) #operational level tensor
tensor_D = tf.random.uniform([4,2], seed =42)

print(tensor_C)

In [ ]:
print(tensor_D)
# the global level seed and the operation level seed provide same tensor whenever it executed. 
# this will enable to produce reproducable tensors

In [ ]:
tensor_1 = tf.constant([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(tensor_1)

In [ ]:
print(tf.random.shuffle(tensor_1, seed= 29)) # shuffeled tensor

#Other ways of creating tensors

In [ ]:
# tensor of all ones 
tf.ones([2,6])

In [ ]:
# Tensors of all zeros 
tf.zeros(shape =(5,6))

### Turn Numpy arrays into tensors 

>The main difference between the Numpy arrys and tensorflow tensors is tensors can run on the GPUS( much faster for numerical computing) 

In [ ]:
# We can convert NUMpy array to tensors
import numpy as np
numpy_A =np.arange(1,25,dtype =np.int32) # creating numpy array between 1 and 25
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y =tf.constant(vector) # non-capital for vector


In [ ]:
# The number of the element in the shape of the tensor must be equal to the numner of element being passed

A = tf.constant(numpy_A, shape =(2,3,4))  # numpy arrays can directly be converted to tensors using this
B = tf.constant(numpy_A)
A,B

In [ ]:
A.ndim,B.ndim

##Getting more information form tensors

* Shape -- **tensor.shape**
* Rank -- **tensor.ndim**
* Axis or dimension -- A particular dimension of tensor -- **tensor[0],tensor[:,1]**
* Size -- total number of element in the tensor -- **tf.size(tensor)**

In [ ]:
# creating a rank 4 tensor 
rank_4_tensor = tf.zeros(shape=(1,2,3,4))
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim , tf.size(rank_4_tensor)

In [ ]:
# Getting various attributes of our tensors
print("data type of every element : ",rank_4_tensor.dtype)
print("Number of dimensions (rank) : ", rank_4_tensor.ndim)
print("Shape of tensor : ", rank_4_tensor.shape)
print("Elements along the zero axis : ", rank_4_tensor.shape[0])
print("Element along the last axis :", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor : ", tf.size(rank_4_tensor).numpy()) 
# We can use *.numpy() method to convert the data into a single number


## Indexing and Expanding tensors
Tensors can be index as python list.

In [ ]:
# we wiil get first two element of each dimension

rank_4_tensor[:2,:2,:2,:2]

In [ ]:
# Get first element from each dimension form each index except for final one
rank_4_tensor[:1,:1,:1]

In [ ]:
# Creating a rank 2 tensor 
rank2tensor = tf.constant([[2,3],[4,6]])
rank2tensor.ndim,rank2tensor

In [ ]:
#Gettig the last element of each dimension

rank2tensor[:,-1]

In [ ]:
# Adding in extra dimension in our rank 2 tensor

rank_3_tensor = rank2tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
#Altenative to tf.new axis i.e tf.expand
rank2tensor,tf.expand_dims(rank2tensor ,axis = 2)

>Adding the extra dimension only changes the the way the data is stored in the tensor it does not effect the actual data inside the tensor

### Mnupulating the tensors // Tensors operations

**Basic Operations** 
+ ,_ , * , /

In [ ]:
#We can add values to a tensor by using addition operator
tensor =tf.constant ([[2,3],[4,7]])
tensor+10

In [ ]:
# we can multiply by utilising the builtin functions
tf.multiply(tensor,10)

**Matrix Multiplication**

In the tensor flow the matrix multiplication is one of the most common tensor operations.

## Now we are going to use the tensor flow to predict the market

In [ ]:
!pip install pyttsx3   # For installing Python text to speech

In [ ]:
!pip install nsetools

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from nsetools import Nse


In [ ]:
market = Nse()

In [ ]:
all_stock_data_name = market.get_stock_codes()
print(all_stock_data_name['AARON'])
print("")
quote = market.get_quote('AARON')
print("Current price is : ",quote['lastPrice'])
quote

Aaron Industries Limited

Current price is :  171.5


{'pricebandupper': 172.3,
 'symbol': 'AARON',
 'applicableMargin': 25.0,
 'bcEndDate': '10-SEP-22',
 'totalSellQuantity': None,
 'adhocMargin': None,
 'companyName': 'Aaron Industries Limited',
 'marketType': 'N',
 'exDate': '01-SEP-22',
 'bcStartDate': '04-SEP-22',
 'css_status_desc': 'Listed',
 'dayHigh': 172.3,
 'basePrice': 164.1,
 'securityVar': 21.23,
 'pricebandlower': 155.9,
 'sellQuantity5': None,
 'sellQuantity4': None,
 'sellQuantity3': None,
 'cm_adj_high_dt': '02-SEP-22',
 'sellQuantity2': None,
 'dayLow': 166.25,
 'sellQuantity1': None,
 'quantityTraded': 3816.0,
 'pChange': 4.51,
 'totalTradedValue': 9.01,
 'deliveryToTradedQuantity': 75.5,
 'totalBuyQuantity': 1.0,
 'averagePrice': 170.16,
 'indexVar': None,
 'cm_ffm': 41.21,
 'purpose': 'ANNUAL GENERAL MEETING/DIVIDEND - RS 0.80 PER SHARE',
 'buyPrice2': None,
 'secDate': '19-Dec-2022 15:00:00',
 'buyPrice1': 171.1,
 'high52': 207.8,
 'previousClose': 164.1,
 'ndEndDate': None,
 'low52': 102.0,
 'buyPrice4': None,
 'bu

In [ ]:
from nsetools import Nse
market = Nse()

name = input("Enter the name of the stock : ")

if name == "":
  name = "infy"

if market.is_valid_code(name) == True :
  quote = market.get_quote(name)
  print(quote['companyName'])
  print("Currrent price is : ", quote['lastPrice'])

else :
  print("The company code does not exist")


Enter the name of the stock : sbin
State Bank of India
Currrent price is :  605.5


In [ ]:
!pip install nsepy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for nsepy: filename=nsepy-0.8-py3-none-any.whl size=36085 sha256=e86f35de27131a2b5d7732f6cf6a6d8436ac665ae38cd0f1ace19c0cda76fcba
  Stored in directory: /root/.cache/pip/wheels/b9/2c/cb/d74199e422a1dbc20297d10cfff9c54d03e0b5c6694d49ccdd
Successfully built nsepy


In [ ]:
import nsepy as market
symbol = "SBIN"
series = "EQ"
start_date = "08-06-2021"
end_date ="14-06-2021"
print(market.equity_history(symbol,series,start_date,end_date))

AttributeError: ignored